name: CI

on:
  push:
    branches: [ "**" ]
    tags: [ "v*", "*.*.*" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: maven

      - name: Build with Maven (compile + test)
        run: mvn -B -U verify

      - name: Upload JAR artifact(s)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: maven-artifacts
          path: |
            target/*.jar
          if-no-files-found: error
          retention-days: 7

      - name: Upload Test Reports (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: |
            target/surefire-reports/**
          if-no-files-found: warn
          retention-days: 7
